### ISSUE TITLE
Cant get it to work across compact machines 

### ISSUE THREAD

**Issue by DiggityMan420** [RuochenFu21/CreateEnderTransmission#1]
i don't think its intended but cant get it to work in compact machines 1.19.2 FTB Skies

From compact machine hooked to a steam engine to my base outside the machine

**Comment by furuochen-dev** [comment]
I think that would be a cross-dimension problem

**Comment by furuochen-dev** [comment]
Where energy transmitter can’t transmit to another dimension

**Comment by DiggityMan420** [comment]
are you? 
Forsteri123

**Comment by gouldcwilliam** [comment]
Yeah, i'm having the same issue as well. trying to move my sifting to a compact machine and it's not transmitting rotation inside the machine
