### ISSUE TITLE
[Probably a bug report] Energy Transmitter doesn't work across dimensions

### ISSUE THREAD

**Issue by Hexality** [RuochenFu21/CreateEnderTransmission#16]
Energy transmitter only works on the same dimension, and refuses to work if you set it on another dimension.

**Minecraft version:** _1.20.1_
**Forge version:** _47.2.23 (Both on client and server)_
**Mod version:** _2.0.7-1.20.1_

**Comment by furuochen-dev** [comment]
work as intended

**Comment by Hexality** [comment]
so you won't add an option to enable it to work across dimensions? lol.

**Comment by furuochen-dev** [comment]
Technical difficulty.
