### ISSUE TITLE
[Request] Fabric port? (or better said update to 1.19.2)

### ISSUE THREAD

**Issue by Wubzzz1337** [RuochenFu21/CreateEnderTransmission#4]
As the title says, are you thinking of maybe also porting it to Fabric or in this case update it to 1.19.2, I see 1.18 already has the tag?

**Comment by furuochen-dev** [comment]
1.19.2 is published on curseforge

**Comment by furuochen-dev** [comment]
But I can't port to fabric, there is a porter working on it

**Comment by CityScrambler** [comment]
> But I can't port to fabric, there is a porter working on it

Do you have any more information on that? Any idea when they will be done porting?

**Comment by furuochen-dev** [comment]
> > But I can't port to fabric, there is a porter working on it
> 
> Do you have any more information on that? Any idea when they will be done porting?

Actually the porter quitted modding, I will port when I have time!

**Comment by furuochen-dev** [comment]
It will be done within next 1 month
